### ISSUE TITLE
Project motivation and goals

### ISSUE THREAD

**Issue by witekest** [monasca/monasca-watchers#1]
@craigbr Could you please shortly explain (here or in README) what are the motivation and goals of this repository? Thanks.

**Comment by craigbr** [comment]
@witekest Updated README coming today.

**Comment by craigbr** [comment]
@witekest Let me know if the README is sufficient or if I need to expand it. Thanks

**Comment by witekest** [comment]
Do we need a dedicated component for that? Is JMX exporter not delivering enough information?

**Comment by craigbr** [comment]
JMX exporter is very expensive to run in a container and it does not verify that Kakfa is actually working in terms of reads and writes succeeding.

**Comment by witekest** [comment]
Thanks
